blank_issues_enabled: true
contact_links:
  - name: Discord Server
    url: https://discord.gg/892GWhTzgs
    about: Ask and answer general questions here.
  
  - name: Security Reports
    url: mailto:rakinar2@onesoftnet.eu.org
    about: Please report security vulnerabilities here.
